#! /bin/bash
/usr/bin/git --git-dir=/home/ubuntu/cw-java-auth/.git --work-tree=/home/ubuntu/cw-java-auth pull
/usr/bin/mvn install -f /home/ubuntu/cw-java-auth/pom.xml
/usr/bin/mvn spring-boot:run -Djava.security.egd=file:/dev/urandom


